<revisionlist>
  <revision rev="1" vrev="1">
    <srcmd5>e383c0810e98538cd5df23b730d13699</srcmd5>
    <version>1.5.0</version>
    <time>1527934107</time>
    <user>dimstar_suse</user>
    <comment>PyTest plugin that activates the fault handler module for tests</comment>
    <requestid>612613</requestid>
  </revision>
  <revision rev="2" vrev="2">
    <srcmd5>45e02acc5e2412dbe66bd85c40021fa9</srcmd5>
    <version>1.5.0</version>
    <time>1550221344</time>
    <user>dimstar_suse</user>
    <comment>- Drop not needed devel BR</comment>
    <requestid>674965</requestid>
  </revision>
  <revision rev="3" vrev="1">
    <srcmd5>bc03ec21bc87a1a82d973adbc7380670</srcmd5>
    <version>1.6.0</version>
    <time>1559581045</time>
    <user>dimstar_suse</user>
    <comment>- Update to 1.6.0:
  * The warning about fault-handler timeout not being supported in some platforms has been moved to the section header (#32).
  * pytest 4.0+ is now required.</comment>
    <requestid>707102</requestid>
  </revision>
  <revision rev="4" vrev="2">
    <srcmd5>3d689ec311dbe586926c3d9c2421c25e</srcmd5>
    <version>1.6.0</version>
    <time>1566479129</time>
    <user>dimstar_suse</user>
    <comment>- Do not pull in pytest 5 as it is integral part of that
  (yet we need it on py3 for pytest3 and pytest4)</comment>
    <requestid>725252</requestid>
  </revision>
</revisionlist>
