<revisionlist>
  <revision rev="1" vrev="1">
    <srcmd5>c9364e85f86385e357bcb6bafe6be773</srcmd5>
    <version>0.11.0</version>
    <time>1559375523</time>
    <user>dimstar_suse</user>
    <comment></comment>
    <requestid>706253</requestid>
  </revision>
  <revision rev="2" vrev="2">
    <srcmd5>7a0ba2cde693d0655957b07f884b00ba</srcmd5>
    <version>0.11.0</version>
    <time>1559580983</time>
    <user>dimstar_suse</user>
    <comment></comment>
    <requestid>707069</requestid>
  </revision>
  <revision rev="3" vrev="1">
    <srcmd5>83af24cd0df9cf87bf798eb345acbcde</srcmd5>
    <version>0.12.1</version>
    <time>1565097112</time>
    <user>dimstar_suse</user>
    <comment></comment>
    <requestid>721100</requestid>
  </revision>
  <revision rev="4" vrev="1">
    <srcmd5>ce213a4736b291f1d36e450c8bf6b60d</srcmd5>
    <version>0.13.0</version>
    <time>1578867851</time>
    <user>dimstar_suse</user>
    <comment>- update to 0.13.0
 * Use slots for memory channel state and statistics which should make
    memory channels slightly smaller and faster. 
 * OpenSSL has a bug in its handling of TLS 1.3 session tickets that can cause
    deadlocks or data loss in some rare edge cases. These edge cases most frequently
    happen during tests.
 * Trio now uses signal.set_wakeup_fd on all platforms.
 * Trio no longer crashes when an async function is implemented in C or Cython
    and then passed directly to trio.run or nursery.start_soon.
 * When a Trio task makes improper use of a non-Trio async library, Trio nowi
    causes an exception to be raised within the task at the point of the error,
    rather than abandoning the task and raising an error in its parent.
    This improves debuggability and resolves the TrioInternalError that would
    sometimes result from the old strategy. (#552)
 * In 0.12.0 we deprecated trio.run_sync_in_worker_thread in favor
    of trio.to_thread.run_sync. But, the deprecation message listed the wrong
    name for the replacement.
 * Fix regression introduced with cancellation changes in 0.12.0, where
    a trio.CancelScope which isn't cancelled could catch a propagating
    trio.Cancelled exception if shielding were changed while the cancellation
    was propagating.
 * Fix a crash that could happen when using MockClock with autojump enabled
    and a non-zero rate.
 * If you nest &gt;1000 cancel scopes within each other, Trio now handles that
    gracefully instead of crashing with a RecursionError.
 * Fixed the hash behavior of trio.Path to match pathlib.Path. Previously
    trio.Path's hash was inherited from object instead of from pathlib.PurePath.</comment>
    <requestid>763378</requestid>
  </revision>
</revisionlist>
