<revisionlist>
  <revision rev="1" vrev="1">
    <srcmd5>7972c4cf80d89504c62452ae2f195777</srcmd5>
    <version>0.4.0</version>
    <time>1528492403</time>
    <user>dimstar_suse</user>
    <comment>Pytest Plugin to Show Failures Instantly</comment>
    <requestid>613427</requestid>
  </revision>
  <revision rev="2" vrev="2">
    <srcmd5>92be2f43fe90de8ab0e6736568e4ac86</srcmd5>
    <version>0.4.0</version>
    <time>1550221359</time>
    <user>dimstar_suse</user>
    <comment>- Really execute the testsuite</comment>
    <requestid>676051</requestid>
  </revision>
  <revision rev="3" vrev="3">
    <srcmd5>4ff933ddc4d0bfaac457eca3a5d29451</srcmd5>
    <version>0.4.0</version>
    <time>1551113490</time>
    <user>coolo</user>
    <comment>- Add patch to fix build with pytest 4.2+:
  * pytest42.patch</comment>
    <requestid>676349</requestid>
  </revision>
  <revision rev="4" vrev="1">
    <srcmd5>54f51d4dd50f157e014052d192d1b711</srcmd5>
    <version>0.4.1</version>
    <time>1551386644</time>
    <user>coolo</user>
    <comment>- Update to 0.4.1:
  * Fixed compatibility with pytest 4.2.0. Thanks @blueyed for the PR.
- Drop merged patch pytest42.patch</comment>
    <requestid>679828</requestid>
  </revision>
  <revision rev="5" vrev="2">
    <srcmd5>5d06d64969b3843e85f4bc14d40b8332</srcmd5>
    <version>0.4.1</version>
    <time>1554749617</time>
    <user>dimstar_suse</user>
    <comment></comment>
    <requestid>692226</requestid>
  </revision>
</revisionlist>
