<revisionlist>
  <revision rev="1" vrev="1">
    <srcmd5>03888cc0d65b9eea2584d6ff04febe9b</srcmd5>
    <version>6.14.0</version>
    <time>1553888098</time>
    <user>dimstar_suse</user>
    <comment></comment>
    <requestid>685015</requestid>
  </revision>
  <revision rev="2" vrev="2">
    <srcmd5>f4688ec6538ee4f40c8977537ec2132a</srcmd5>
    <version>6.14.0</version>
    <time>1590650237</time>
    <user>maxlin_factory</user>
    <comment></comment>
    <requestid>809379</requestid>
  </revision>
  <revision rev="3" vrev="1">
    <srcmd5>85a363dabded744a0bbd3c2c70f8138c</srcmd5>
    <version>6.14.1</version>
    <time>1600347124</time>
    <user>dimstar_suse</user>
    <comment>- update to 6.14.1:
  * Fixed all warnings about importing from collections on Python 3</comment>
    <requestid>835101</requestid>
  </revision>
  <revision rev="4" vrev="2">
    <srcmd5>a0de62bec779a9f776ac85004d5e0179</srcmd5>
    <version>6.14.1</version>
    <time>1621201322</time>
    <user>dimstar_suse</user>
    <comment></comment>
    <requestid>893470</requestid>
  </revision>
  <revision rev="5" vrev="3">
    <srcmd5>d7c2b492901b6d5540213fda957a3234</srcmd5>
    <version>6.14.1</version>
    <time>1630324515</time>
    <user>dimstar_suse</user>
    <comment>- Problems with gh#pipermerriam/flex#234 are not isolated just to
  Python 3.9.
</comment>
    <requestid>914915</requestid>
  </revision>
</revisionlist>
