<revisionlist>
  <revision rev="1" vrev="1">
    <srcmd5>98217fb37656e798721a547d7a211180</srcmd5>
    <version>4.3</version>
    <time>1564994327</time>
    <user>dimstar_suse</user>
    <comment></comment>
    <requestid>720478</requestid>
  </revision>
  <revision rev="2" vrev="2">
    <srcmd5>3cb14bdd0a40a6b4b4be3bfb05e7dfc2</srcmd5>
    <version>4.3</version>
    <time>1621439382</time>
    <user>dimstar_suse</user>
    <comment></comment>
    <requestid>894335</requestid>
  </revision>
  <revision rev="3" vrev="1">
    <srcmd5>55985e28429ff502412e819a67d7b102</srcmd5>
    <version>4.5</version>
    <time>1659470979</time>
    <user>dimstar_suse</user>
    <comment></comment>
    <requestid>992336</requestid>
  </revision>
  <revision rev="4" vrev="1">
    <srcmd5>efdf7c6189441c3b2264bc99b2bf2bec</srcmd5>
    <version>4.7</version>
    <time>1667306529</time>
    <user>dimstar_suse</user>
    <comment></comment>
    <requestid>1032485</requestid>
  </revision>
  <revision rev="5" vrev="1">
    <srcmd5>5207f76cd526c42447f8a8afae2dd2db</srcmd5>
    <version>4.9</version>
    <time>1672859907</time>
    <user>dimstar_suse</user>
    <comment>- update to 4.9:
  * Fix regression in 4.7 on Python 2 when calling ``asdatetime``.
  (`#47 &lt;https://github.com/zopefoundation/DateTime/issues/47&gt;`_)
  * Fix insidious buildout configuration bug that prevented tests on Python
    2.7 and 3.5, and fix test code that was incompatible with Python 3.5.
  * Add support for Python 3.11.</comment>
    <requestid>1055952</requestid>
  </revision>
</revisionlist>
